#!/usr/bin/env bash
# Ballast SFTP destination integration test: proves an
# "sftp:user@host:path" destination URL actually works end to end against a
# real SFTP server, not just that restic's local and S3 backends do
# (run.sh, run-s3.sh). Destination.URL is engine-native and opaque to
# Ballast (internal/config's own doc comment: "engine syntax is
# deliberately quarantined here"), so nothing in Ballast's own code
# branches on the URL scheme -- but that also means nothing had ever
# actually exercised the sftp: scheme before this test, and restic's sftp
# backend has a real, non-obvious runtime dependency Ballast's own image
# didn't carry: it execs the "ssh" binary on PATH to open the connection
# (see the Dockerfile's openssh-client comment; this test is what found
# that gap -- see docs/TESTING.md's "Bugs found and fixed").
#
# It stands up a throwaway atmoz/sftp server on a "ballast-itest-net" user
# network, authenticated with a fresh, itest-only Ed25519 keypair generated
# each run (public key mounted into the SFTP server, private key plus an
# ~/.ssh/config mounted into every "ballast" invocation), backs up a
# labeled service to it, confirms real files landed on the SFTP server's
# own filesystem (via docker exec into the SFTP container, independent of
# Ballast's own view), and restores + byte-diffs the canary.
#
# What this does NOT prove about host-key handling: the itest config
# disables strict host-key checking (StrictHostKeyChecking=no,
# UserKnownHostsFile=/dev/null) since the SFTP server's host key is
# regenerated by atmoz/sftp on every throwaway run and pinning it isn't
# this test's concern. A real deployment should pin the real server's host
# key (a "Host <name>\n  HostKeyAlias ...\n  UserKnownHostsFile ..." entry
# in its own ssh config) rather than copy this test's disabled checking.
#
# Every Docker object this script creates is named with the prefix
# "ballast-itest-" (containers, network) or tagged "ballast:itest" (image).
# It never touches any other container, network, or image. Cleanup runs on
# exit (success, failure, or interrupt) via the trap below.
#
# Usage: test/integration/run-sftp.sh [--keep]
#   --keep  skip cleanup at the end (for debugging a failure)

set -euo pipefail

HARNESS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HARNESS_DIR/../.." && pwd)"

KEEP=0
for arg in "$@"; do
  case "$arg" in
    --keep) KEEP=1 ;;
    *) echo "unknown argument: $arg" >&2; exit 2 ;;
  esac
done

NET=ballast-itest-net
SFTP=ballast-itest-sftp
SVC=ballast-itest-sftp-svc
VOL=ballast-itest-sftp-data
IMAGE=ballast:itest
CFG="$HARNESS_DIR/sftp.itest.yml"
SECRETS="$HARNESS_DIR/secrets"
RESTORE="$HARNESS_DIR/restore-sftp"
SSHDIR="$HARNESS_DIR/ssh-sftp"

log() { printf '\n=== %s ===\n' "$1"; }

cleanup() {
  if [ "$KEEP" -eq 1 ]; then
    log "skipping cleanup (--keep); remove ballast-itest-* by hand when done"
    return
  fi
  log "cleanup"
  docker rm -f "$SVC" "$SFTP" >/dev/null 2>&1 || true
  docker volume rm "$VOL" >/dev/null 2>&1 || true
  docker network rm "$NET" >/dev/null 2>&1 || true
  rm -rf "${SSHDIR:?}"/* "${RESTORE:?}"/* 2>/dev/null || true
}
trap cleanup EXIT

# --- host layout ------------------------------------------------------------

log "checking Docker volumes root"
DOCKER_ROOT="$(docker info --format '{{.DockerRootDir}}')"
VOLUMES_ROOT="$DOCKER_ROOT/volumes"
if [ "$VOLUMES_ROOT" != "/var/lib/docker/volumes" ]; then
  echo "NOTE: volumes root differs from the default baked into sftp.itest.yml (/var/lib/docker/volumes)." >&2
  echo "      Add a host_roots entry mapping $VOLUMES_ROOT to itself before running this harness." >&2
  exit 1
fi

mkdir -p "$SECRETS" "$RESTORE" "$SSHDIR"

# --- secrets -----------------------------------------------------------------

if [ ! -s "$SECRETS/repo-master-key" ]; then
  log "generating repo-master-key"
  openssl rand -base64 32 > "$SECRETS/repo-master-key"
fi

# --- fresh itest-only SSH keypair, regenerated every run ---------------------

log "generating a fresh Ed25519 keypair for this run"
rm -f "$SSHDIR/id_ed25519" "$SSHDIR/id_ed25519.pub" "$SSHDIR/config"
ssh-keygen -q -t ed25519 -N "" -C "ballast-itest-sftp" -f "$SSHDIR/id_ed25519"
chmod 600 "$SSHDIR/id_ed25519"

cat > "$SSHDIR/config" <<EOF
Host *
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
    IdentityFile /root/.ssh/id_ed25519
    User sftpuser
EOF
chmod 644 "$SSHDIR/config"

# --- build ---------------------------------------------------------------

log "building $IMAGE"
docker build -f "$REPO_ROOT/Dockerfile" -t "$IMAGE" "$REPO_ROOT"

# --- network + SFTP server ---------------------------------------------------

log "creating $NET"
docker network rm "$NET" >/dev/null 2>&1 || true
docker network create "$NET" >/dev/null

log "starting $SFTP (atmoz/sftp, public-key auth only)"
docker rm -f "$SFTP" >/dev/null 2>&1 || true
docker run -d --name "$SFTP" \
  --network "$NET" \
  -v "$SSHDIR/id_ed25519.pub":/home/sftpuser/.ssh/keys/id_ed25519.pub:ro \
  atmoz/sftp \
  sftpuser::1001:1001:upload

log "waiting for $SFTP to accept SSH connections"
READY=0
for i in $(seq 1 30); do
  if docker run --rm --network "$NET" \
      -v "$SSHDIR":/root/.ssh:ro \
      --entrypoint ssh \
      "$IMAGE" -o BatchMode=yes -o ConnectTimeout=2 sftpuser@"$SFTP" -s sftp </dev/null >/dev/null 2>&1; then
    READY=1
    break
  fi
  sleep 1
done
if [ "$READY" -ne 1 ]; then
  echo "FAIL: $SFTP never accepted an SFTP connection within 30s" >&2
  docker logs "$SFTP" 2>&1 | tail -40 >&2
  exit 1
fi
echo "PASS: $SFTP is accepting SFTP connections over the fresh keypair"

# --- test service --------------------------------------------------------

log "creating $SVC with canary data in $VOL"
docker rm -f "$SVC" >/dev/null 2>&1 || true
docker volume rm "$VOL" >/dev/null 2>&1 || true
docker run -d --name "$SVC" \
  -v "$VOL":/data \
  --label ballast.enable=true \
  --label ballast.repo=sftp \
  busybox sh -c 'mkdir -p /data && echo "ballast-itest-sftp-canary-$(date +%s)" > /data/canary.txt && sleep 3600'

sleep 1
ORIGINAL_CANARY="$(docker exec "$SVC" cat /data/canary.txt)"
echo "canary: $ORIGINAL_CANARY"

ballast() {
  docker run --rm \
    --network "$NET" \
    -v /var/run/docker.sock:/var/run/docker.sock:ro \
    -v "$VOLUMES_ROOT":"$VOLUMES_ROOT":ro \
    -v "$SSHDIR":/root/.ssh:ro \
    -v "$SECRETS":/run/ballast/secrets:ro \
    -v "$CFG":/etc/ballast/ballast.yml:ro \
    -v "$RESTORE":/restore \
    "$IMAGE" "$@" --config /etc/ballast/ballast.yml
}

# --- backup ------------------------------------------------------------------

log "ballast backup $SVC (destination sftp, real SFTP server)"
ballast backup "$SVC"

# --- confirm real files landed on the SFTP server, independent of Ballast ---

log "checking the SFTP server's own filesystem for the repository"
FILE_COUNT="$(docker exec "$SFTP" sh -c 'find /home/sftpuser/upload/repos -type f 2>/dev/null | wc -l')"
echo "files under /upload/repos on the SFTP server: $FILE_COUNT"
if [ "$FILE_COUNT" -eq 0 ]; then
  echo "FAIL: no files found on the SFTP server after backup" >&2
  docker exec "$SFTP" sh -c 'find /home/sftpuser/upload 2>/dev/null' >&2 || true
  exit 1
fi
if ! docker exec "$SFTP" sh -c "test -f /home/sftpuser/upload/repos/$SVC/config"; then
  echo "FAIL: no restic config object found at /upload/repos/$SVC/config on the SFTP server" >&2
  exit 1
fi
echo "PASS: a real, initialized restic repository exists on the SFTP server's own filesystem"

# --- snapshots ---------------------------------------------------------------

log "ballast snapshots $SVC"
SNAP_OUT="$(ballast snapshots "$SVC")"
echo "$SNAP_OUT"
if [ "$(echo "$SNAP_OUT" | tail -n +2 | grep -c .)" -eq 0 ]; then
  echo "FAIL: ballast snapshots reported none from the SFTP destination" >&2
  exit 1
fi
echo "PASS: ballast snapshots lists the snapshot from the SFTP repository"

# --- restore -------------------------------------------------------------

log "ballast restore $SVC"
ballast restore "$SVC" --target /restore

RESTORED_FILE="$(find "$RESTORE" -name canary.txt | head -1)"
if [ -z "$RESTORED_FILE" ]; then
  echo "FAIL: canary.txt not found under $RESTORE after restore" >&2
  exit 1
fi
RESTORED_CANARY="$(cat "$RESTORED_FILE")"

echo "original canary:  $ORIGINAL_CANARY"
echo "restored canary:  $RESTORED_CANARY"
if [ "$ORIGINAL_CANARY" != "$RESTORED_CANARY" ]; then
  echo "FAIL: restored canary does not match the original" >&2
  exit 1
fi
echo "PASS: restored canary byte-matches the original, from a real SFTP backend"

log "done"
